version: '3'
services:
  bond:
    image: mosswill/bond:latest
    networks:
      - global
    expose:
      - 80
    environment:
      PORT: "80"
      SECRET: "<PLACEHOLDER>"

      VIRTUAL_HOST: "your-domain.tld"
      VIRTUAL_PORT: "80"
      # Depending on your setup, you may also need
      # CERT_NAME: "default"
      # Or even
      # LETSENCRYPT_HOST: "your-domain.tld"

  proxy:
    image: jwilder/nginx-proxy
    networks:
      - global
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  # Assumption made : network "global" is created beforehand
  # with            : docker network create global
  global:
    external: true
